/* eslint-disable */
/**
 * Generated by `csvx codegen --lang ts` from csvx-spec/schemas/*.schema.json.
 * DO NOT EDIT BY HAND. Modify the schema and regenerate instead — see
 * csvx-spec/AGENTS.md rule 3.1 for why this file must never be hand-typed.
 */

export interface CSVXFormulaCell {
  formula: string;
  cached?: Value;
  [k: string]: unknown;
}

export interface Value {
  type: "blank" | "boolean" | "integer" | "decimal" | "string" | "date" | "time" | "datetime" | "error";
  value?: unknown;
  code?: string;
  message?: string;
  [k: string]: unknown;
}

export interface CSVXManifest {
  format: "csvx";
  version: "1.0";
  workbook: "workbook.json";
  files: string[];
  [k: string]: unknown;
}

export type Id = string;

export type ScalarType =
  "blank" | "boolean" | "integer" | "decimal" | "string" | "date" | "time" | "datetime" | "error";

export interface CSVXSheetMetadata {
  id?: Id;
  name?: string;
  columns?: Column[];
  rowHeights?: {
    [k: string]: number;
  };
  cells?: {
    [k: string]: Cell;
  };
  [k: string]: unknown;
}

export interface Column {
  id: string;
  name?: string;
  type?: ScalarType;
  width?: number;
  [k: string]: unknown;
}

export interface Cell {
  type?: ScalarType;
  formula?: string;
  cached?: Value;
  style?: Id;
  validation?: Validation;
  [k: string]: unknown;
}

export interface Validation {
  type?: "whole" | "decimal" | "list" | "date" | "textLength" | "custom";
  allowBlank?: boolean;
  operator?: string;
  formula1?: string;
  formula2?: string;
  message?: string;
  [k: string]: unknown;
}

export interface CSVXStyles {
  styles: {
    id: string;
    numberFormat?: string;
    font?: {
      [k: string]: unknown;
    };
    fill?: {
      [k: string]: unknown;
    };
    border?: {
      [k: string]: unknown;
    };
    alignment?: {
      [k: string]: unknown;
    };
    protection?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

export interface CSVXWorkbook {
  id: Id;
  version: "1.0";
  /**
   * @minItems 1
   */
  sheets: [
    {
      id: Id;
      name: string;
      path: string;
      metadata?: string;
      [k: string]: unknown;
    },
    ...{
      id: Id;
      name: string;
      path: string;
      metadata?: string;
      [k: string]: unknown;
    }[]
  ];
  calculation?: {
    mode?: "automatic" | "manual" | "on-load";
    iteration?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
