/* eslint-disable */
/**
 * Generated by `csvx codegen --lang ts` from csvx-spec/schemas/*.schema.json.
 * DO NOT EDIT BY HAND. Modify the schema and regenerate instead — see
 * csvx-spec/AGENTS.md rule 3.1 for why this file must never be hand-typed.
 */

export interface CSVXFormulaCell {
  formula: string;
  cached?: Value;
  [k: string]: unknown;
}

export interface Value {
  type: "blank" | "boolean" | "integer" | "decimal" | "string" | "date" | "time" | "datetime" | "error";
  value?: unknown;
  code?: string;
  message?: string;
  [k: string]: unknown;
}

export interface CSVXManifest {
  format: "csvx";
  version: "1.0";
  workbook: "workbook.json";
  files: string[];
  [k: string]: unknown;
}

export type Id = string;

export type ScalarType =
  "blank" | "boolean" | "integer" | "decimal" | "string" | "date" | "time" | "datetime" | "error";

export interface CSVXSheetMetadata {
  id?: Id;
  name?: string;
  columns?: Column[];
  /**
   * Row height by 1-based row number, in points (XLSX's own unit; its default row height is 15pt) — see spec/03-sheets.md.
   */
  rowHeights?: {
    [k: string]: number;
  };
  print?: Print;
  cells?: {
    [k: string]: Cell;
  };
  [k: string]: unknown;
}

export interface Column {
  id: string;
  name?: string;
  type?: ScalarType;
  /**
   * XLSX character-width units (the number of '0' glyphs, in the workbook's default font, that fit the column, plus padding) — see spec/03-sheets.md for the canonical pixel conversion formula every engine must use.
   */
  width?: number;
  [k: string]: unknown;
}
/**
 * Print and pagination settings — see spec/03-sheets.md (Print settings) and spec/14-xlsx-interoperability.md.
 */

export interface Print {
  orientation?: "portrait" | "landscape";
  paperSize?: "letter" | "legal" | "tabloid" | "a3" | "a4" | "a5";
  /**
   * Inches, the unit XLSX uses.
   */
  margins?: {
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
    [k: string]: unknown;
  };
  scale?: number;
  fitToWidth?: number;
  fitToHeight?: number;
  area?: string;
  repeatRows?: string;
  repeatColumns?: string;
  pageOrder?: "downThenOver" | "overThenDown";
  gridlines?: boolean;
  centerHorizontally?: boolean;
  columnBreaks?: number[];
  rowBreaks?: number[];
  [k: string]: unknown;
}

export interface Cell {
  type?: ScalarType;
  formula?: string;
  cached?: Value;
  style?: Id;
  validation?: Validation;
  [k: string]: unknown;
}

export interface Validation {
  type?: "whole" | "decimal" | "list" | "date" | "textLength" | "custom";
  allowBlank?: boolean;
  operator?: string;
  formula1?: string;
  formula2?: string;
  message?: string;
  [k: string]: unknown;
}

export type BorderLineStyle = "none" | "thin" | "medium" | "thick" | "dashed" | "dotted" | "double";

export interface CSVXStyles {
  styles: {
    id: string;
    numberFormat?: string;
    font?: {
      name?: string;
      /**
       * Font size in points (spec/08-styles.md); default 11.
       */
      size?: number;
      bold?: boolean;
      italic?: boolean;
      underline?: boolean;
      color?: string;
      [k: string]: unknown;
    };
    fill?: {
      [k: string]: unknown;
    };
    border?: {
      style?: BorderLineStyle;
      color?: string;
      top?: BorderEdge;
      right?: BorderEdge;
      bottom?: BorderEdge;
      left?: BorderEdge;
      [k: string]: unknown;
    };
    alignment?: {
      [k: string]: unknown;
    };
    protection?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

export interface BorderEdge {
  style?: BorderLineStyle;
  color?: string;
  [k: string]: unknown;
}

export interface CSVXWorkbook {
  id: Id;
  version: "1.0";
  /**
   * @minItems 1
   */
  sheets: [
    {
      id: Id;
      name: string;
      path: string;
      metadata?: string;
      [k: string]: unknown;
    },
    ...{
      id: Id;
      name: string;
      path: string;
      metadata?: string;
      [k: string]: unknown;
    }[]
  ];
  /**
   * Workbook-scoped names — spec/02-workbook.md (Named ranges).
   */
  namedRanges?: {
    /**
     * Must also not look like a cell reference, be TRUE or FALSE, or be a Core function name, and must be unique ignoring case (spec/02-workbook.md).
     */
    name: string;
    /**
     * A formula expression with sheet-qualified references (spec/02-workbook.md).
     */
    refersTo: string;
    [k: string]: unknown;
  }[];
  /**
   * Provenance of an imported workbook (spec/14-xlsx-interoperability.md, 14.1); also written to source/source.json.
   */
  source?: {
    format: "xlsx" | "xlsm";
    filename: string;
    sha256: string;
    importedAt: string;
    importer: string;
    authority: "original" | "csvx";
    features?: {
      [k: string]: unknown;
    };
    mappings?: unknown;
    warnings?: unknown[];
    [k: string]: unknown;
  };
  calculation?: {
    mode?: "automatic" | "manual" | "on-load";
    iteration?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
